local plugins = {
	 {'stevearc/aerial.nvim'},
	 {'windwp/nvim-autopairs'},
	 {'Pocco81/AutoSave.nvim'},
	 {'rmagatti/auto-session'},
	 {'famiu/bufdelete.nvim'},
	 {'lukas-reineke/indent-blankline.nvim'},
	 {'max397574/better-escape.nvim',event = 'InsertEnter'},
	 {'akinsho/bufferline.nvim'},
	 {'norcalli/nvim-colorizer.lua',opt = true},
	 {'sindrets/diffview.nvim'},
	 {'lewis6991/gitsigns.nvim',
	 	requires = 'nvim-lua/plenary.nvim'},
	 {'terrortylor/nvim-comment'},
	 {"kyazdani42/nvim-tree.lua",
	 	 requires = {"kyazdani42/nvim-web-devicons"}},
	 {'edluffy/specs.nvim'},
	 {"nvim-treesitter/nvim-treesitter",run = ':TSUpdate',
	 requires = {
		 {"nvim-treesitter/nvim-treesitter-refactor",after = 'nvim-treesitter'},
		 {'nvim-treesitter/nvim-treesitter-textobjects'},
	         {'windwp/nvim-ts-autotag',after = 'nvim-treesitter'},
	         {'p00f/nvim-ts-rainbow',after = 'nvim-treesitter'},
		 {'andymass/vim-matchup',after = 'nvim-treesitter'}}},
	 {'romgrk/nvim-treesitter-context'},
	 {'abecodes/tabout.nvim'},
	 {'folke/twilight.nvim'},
	 {'gelguy/wilder.nvim',
		 requires = {'roxma/nvim-yarp',
			 'roxma/vim-hug-neovim-rpc',
			 'romgrk/fzy-lua-native'}, run = 'pip install --user pyre2'},

	 {"goolord/alpha-nvim"},
	 {'lewis6991/impatient.nvim',
	 	config = function()
			require'impatient'.enable_profile()
		end},
	 {'iamcco/markdown-preview.nvim',run = 'cd app && yarn install'},
	 {"rcarriga/nvim-notify"},
	 {"nvim-telescope/telescope.nvim",
	 requires = {{"sharkdp/fd"},
		    {"BurntSushi/ripgrep"},
	    	    {'jvgrootveld/telescope-zoxide'}}},
	 {"akinsho/toggleterm.nvim"},
	 {'xiyaowong/nvim-transparent'},


	{"neovim/nvim-lspconfig"},
	{"williamboman/nvim-lsp-installer"},



	{"catppuccin/nvim",as = "catppuccin"},
	{"projekt0n/circles.nvim"},
	{"nvim-lualine/lualine.nvim",
	requires = {'arkav/lualine-lsp-progress',
		   {'SmiteshP/nvim-gps'}}},
	{"EdenEast/nightfox.nvim"},
	{'shaunsingh/nord.nvim'},
	{"folke/tokyonight.nvim"},


	{'hrsh7th/nvim-cmp',
	requires = {
		{'zbirenbaum/copilot.lua',after = 'nvim-cmp',event = 'VimEnter'},
		{'zbirenbaum/copilot-cmp',after = {'nvim-cmp','copilot.lua'}},
		{'hrsh7th/cmp-buffer',after = 'nvim-cmp'},
		{'saadparwaiz1/cmp_luasnip',after = 'LuaSnip'},
		{'hrsh7th/cmp-nvim-lsp',after = 'cmp_luasnip'},
		{'hrsh7th/cmp-nvim-lua',after ='cmp-nvim-lsp'},
		{'hrsh7th/cmp-path',after = 'nvim-cmp'},
		{'f3fora/cmp-spell',after = 'nvim-cmp'},
		{'rafamadriz/friendly-snippets',after = 'nvim-cmp'}}},
		{'L3MON4D3/LuaSnip'},
	{'michaelb/sniprun',run = 'bash ./install.sh &'},
	{'RishabhRD/nvim-lsputils', requires = 'RishabhRD/popfix'},
	{'ray-x/lsp_signature.nvim'},
	{'folke/trouble.nvim'},
	 'rhysd/accelerated-jk',
	  'github/copilot.vim',
	 'onsails/lspkind-nvim',
	 'mbbill/undotree',
	 'itchyny/vim-cursorword',
	 'dstein64/vim-startuptime',
	 'vimwiki/vimwiki',
}
return plugins
